# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: camohe90@gmail.com
author_name: Camilo Molano
contract_name: insurance
deployment_language: python
preset_name: production
project_name: insurance

